command: docker trust key
short: Manage keys for signing Docker images (experimental)
long: Manage keys for signing Docker images (experimental)
usage: docker trust key
pname: docker trust
plink: docker_trust.yaml
cname:
- docker trust key generate
- docker trust key load
clink:
- docker_trust_key_generate.yaml
- docker_trust_key_load.yaml
deprecated: false
experimental: false

