name: Docker Documentation
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
permalink: pretty
safe: false
lsi: false
url: https://docs.docker.com
incremental: false

# Component versions -- address like site.docker_ce_stable_version
# You can't have - characters in these for non-YAML reasons

# TO USE ME:
# jekyll serve --incremental --config _config_authoring.yml

docker_ce_stable_version: "17.09"
latest_stable_docker_engine_api_version: "1.32"
docker_ce_edge_version: "17.09"
docker_ee_version: "17.06"
compose_version: "1.16.1"
machine_version: "0.12.2"
distribution_version: "2.6"

ucp_versions:
  - version: "2.2"
    latest: true
    path: /datacenter/ucp/2.2/guides/
  - version: "2.1"
    path: /datacenter/ucp/2.1/guides/
  - version: "2.0"
    path: /datacenter/ucp/2.0/guides/
  - version: "1.1"
    path: /datacenter/ucp/1.1/overview/

dtr_versions:
  - version: "2.3"
    latest: true
    path: /datacenter/dtr/2.3/guides/
  - version: "2.2"
    path: /datacenter/dtr/2.2/guides/
  - version: "2.1"
    path: /datacenter/dtr/2.1/guides/
  - version: "2.0"
    path: /datacenter/dtr/2.0/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      defaultassignee: johndmulhausen
      toc_min: 2
      toc_max: 3
      tree: true
  - scope:
      path: "engine"
    values:
      win_server_zip_url: "https://download.docker.com/components/engine/windows-server/17.06/docker-17.06.2-ee-4.zip"
  - scope:
      path: "datacenter"
    values:
      ucp_latest_image: "docker/ucp:2.2.3"
      dtr_latest_image: "docker/dtr:2.3.4"
      enterprise: true
  - scope:
      path: "datacenter/dtr/2.3"
    values:
      dtr_org: "docker"
      dtr_repo: "dtr"
      dtr_version: "2.3.4"
  - scope:
      path: "datacenter/dtr/2.2"
    values:
      ucp_version: "2.1"
      dtr_version: "2.2"
      docker_image: "docker/dtr:2.2.9"
  - scope:
      path: "datacenter/dtr/2.1"
    values:
      ucp_version: "2.0"
      dtr_version: "2.1"
  - scope:
      path: "datacenter/dtr/2.0"
    values:
      ucp_version: "1.1"
      dtr_version: "2.0"
  - scope:
      path: "datacenter/ucp/2.2"
    values:
      ucp_org: "docker"
      ucp_repo: "ucp"
      ucp_version: "2.2.3"
  - scope:
      path: "datacenter/ucp/2.1"
    values:
      ucp_version: "2.1"
      dtr_version: "2.2"
      docker_image: "docker/ucp:2.1.5"
  - scope:
      path: "datacenter/ucp/2.0"
    values:
      ucp_version: "2.0"
      dtr_version: "2.1"
      docker_image: "docker/ucp:2.0.3"
  - scope:
      path: "datacenter/ucp/1.1"
    values:
      ucp_version: "1.1"
      dtr_version: "2.0"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
